### ISSUE TITLE
uploadasset.php does not return asset version, only asset id

### ISSUE THREAD

**Issue by ThrownException** [Voidacity/RbxPHP#4]
uploadAsset.php currently only gets the asset's ID, not the AssetID version. ROBLOX might have updated their APIs.

**Comment by Voidacity** [comment]
Yeah ROBLOX updated their API few days ago. Adding &json=1 to the upload URL will make it return the assetId as well as it's assetVersionId.

**Comment by ThrownException** [comment]
I think you should add that because people inexperienced with php or the
ROBLOX api might not be able to figure this one out.

Thanks for the tip I will definitely add this to the script.
